% This demo is provided for image preprocessing of SMU-Net.
% You can easily get the foreground & background saliency maps.
% You are free to use, change or redistribute this code for any
% non-commrecial purposes.If you use this software,please cite the
% following in any resulting publication:
% [1] Ning, Zhenyuan and Zhong, Shengzhou and Feng, Qianjin and Chen, Wufan and Zhang, Yu, 
%     SMU-Net: Saliency-Guided Morphology-Aware U-Net for Breast Lesion Segmentation in Ultrasound Image,
%     IEEE Transactions on Medical Imaging,2021


clear all;clc;close all;
fprintf('running LSCS to get low-level map\n');
file_path = './original/';% original image path
mcg_sp_path = './sp_high/';% high-level image path, which are generated by MCG
img_path_list = dir(strcat(file_path,'*.png'));
img_num = length(img_path_list);
fore_sal_path = './process/foreground/';
back_sal_path = './process/background/';
mkdir(fore_sal_path);
mkdir(back_sal_path);
        
if img_num > 0 
    gaus=fspecial('gaussian',3);
    ratio=0.075; 
    for j = 1:img_num
        image_name = img_path_list(j).name;
        img = imread(strcat(file_path,image_name)); 
        fprintf('%d %s\n',j,strcat(file_path,image_name));
        if (length(size(img))<3)
            img=repmat(img,[1,1,3]);
        end
        I=imfilter(img,gaus);
        coordinate=xlsread('./point_original.xls','Sheet1','B1:G10');
        lsc_8=LSC_mex(I,8,ratio);
        lsc_15=LSC_mex(I,15,ratio);
        lsc_50=LSC_mex(I,50,ratio);
        [m,n]=size(lsc_8);
        sp_8 = zeros(size(lsc_8));
        sp_15 = zeros(size(lsc_8));
        sp_50 = zeros(size(lsc_8));
        for x=1:m
            for y=1:n
                if sp_8(x,y)==lsc_8(coordinate(j,1),coordinate(j,2)) || lsc_8(x,y)==lsc_8(coordinate(j,3),coordinate(j,4)) || lsc_8(x,y)==lsc_8(coordinate(j,5),coordinate(j,6))
                    sp_8(x,y)=255;
                end
                if sp_15(x,y)==lsc_15(coordinate(j,1),coordinate(j,2)) || lsc_15(x,y)==lsc_15(coordinate(j,3),coordinate(j,4)) || lsc_15(x,y)==lsc_15(coordinate(j,5),coordinate(j,6))
                    sp_15(x,y)=255;
                end
                if sp_50(x,y)==lsc_50(coordinate(j,1),coordinate(j,2)) || lsc_50(x,y)==lsc_50(coordinate(j,3),coordinate(j,4)) || lsc_50(x,y)==lsc_50(coordinate(j,5),coordinate(j,6))
                    sp_50(x,y)=255;
                end
            end
        end
        merge = sp_8+sp_15+sp_50;       
        lsc_low=double(Normalize(merge));%generated low-level map
        mcg_high = double(imread(strcat(mcg_sp_path,image_name)));%read high-level map
        fore_sal=lsc_low+0.5*mcg_high;%merge low- and high-level maps to get foreground saliency map
        fore_sal = uint8(Normalize(fore_sal));
        back_sal = 255-fore_sal;% generate background map
        imwrite(fore_sal,[fore_sal_path,image_name],'png');
        imwrite(back_sal,[back_sal_path,image_name],'png');
    end
else
    fprintf('%s\n','No file exists in this dir, please check your dir.')
end
